apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-0.kafka.default.svc.cluster.local:9092,PLAINTEXT://kafka-1.kafka.default.svc.cluster.local:9092,PLAINTEXT://kafka-2.kafka.default.svc.cluster.local:9092
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka/data
      volumes:
        - name: data
          emptyDir: {}
